Add an extra check to check alias

diff --git a/src/aux/scheduler b/src/aux/scheduler
--- a/src/aux/scheduler
+++ b/src/aux/scheduler
@@ -53,7 +53,8 @@ get_node_list()
         REMORA_SCHEDULER=none
         REMORA_JOB_ID=`date +%s`
         NODES=`hostname -a`
-        if [[ -z "${NODES// }" ]]; then
+        # Checking the output and return value (Macs don't work well with -a)
+        if [[ -z "${NODES// }" ]] || [ "$?" == "1" ]; then
             NODES=`hostname`
             # If nothing, at least try localhost
             if [[ -z "${NODES// }" ]]; then
